openapi: 3.1.0
info:
  title: SharePoint File Parser
  version: 3.0.0
  description: |
    This function allows GPTs to list SharePoint files and parse them by fileId.
    Use `list=true` to browse files, then `fileId=...` to retrieve content.
    `filename` is no longer supported to prevent errors.

servers:
  - url: https://serina-function.azurewebsites.net

paths:
  /api/HttpTrigger1:
    get:
      operationId: handleSharePoint
      summary: List or retrieve SharePoint files
      parameters:
        - name: fileId
          in: query
          required: false
          schema:
            type: string
          description: SharePoint file ID to fetch and parse
        - name: summary
          in: query
          required: false
          schema:
            type: boolean
          description: If true, truncates the parsed content
        - name: debug
          in: query
          required: false
          schema:
            type: boolean
          description: If true, includes Graph fetch URL
        - name: list
          in: query
          required: false
          schema:
            type: boolean
          description: If true, returns a list of available files
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ParsedContent"
                  - $ref: "#/components/schemas/FileList"
                  - $ref: "#/components/schemas/StatusResponse"
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Server error

components:
  schemas:
    ParsedContent:
      type: object
      required: [content]
      properties:
        content:
          type: string
        contentUrl:
          type: string

    FileMetadata:
      type: object
      required: [name, fileId, type, lastModified, path]
      properties:
        name:
          type: string
        fileId:
          type: string
        type:
          type: string
        lastModified:
          type: string
          format: date-time
        path:
          type: string

    FileList:
      type: array
      items:
        $ref: "#/components/schemas/FileMetadata"

    StatusResponse:
      type: object
      required: [status, message]
      properties:
        status:
          type: string
        message:
          type: string
